server:
  port: 8081

spring:
  application:
    name: zhufeng-resume-backend

  # PostgreSQL 数据库配置（改成你自己的）
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zhufeng_resume
    username: postgres
    password: 123456

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhufeng.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.zhufeng: debug
    org.springframework: info
